app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage
