###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: knp-university-memcached

    redis:
      image: redis:alpine
      container_name: knp-university-redis

    mysql:
      image: mysql:8.0
      container_name: knp-university-mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=knp_university
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root

    adminer:
      image: hardware/adminer
      container_name: adminer
      ports:
        - "8888:8888"
      links:
        - mysql

    webserver:
      image: nginx:alpine
      container_name: knp-university-webserver
      working_dir: /application
      volumes:
          - ..:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ../var/logs:/var/log/nginx/
      ports:
       - "1080:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      container_name: knp-university-php-fpm
      working_dir: /application
      volumes:
        - ..:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      depends_on:
        - memcached
        - mysql
        - redis
      links:
        - memcached
        - mysql
        - redis
